export const APP_NAME = "OControle";
export const APP_DESCRIPTION =
  "Plateforme SaaS de pointage et gestion de présence pour les entreprises africaines";
export const APP_URL = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";

export const DEFAULT_CURRENCY = "XOF";
export const DEFAULT_TIMEZONE = "Africa/Abidjan";
export const DEFAULT_LOCALE = "fr";
export const DEFAULT_COUNTRY = "CI";

export const TRIAL_DAYS = 14;
export const GRACE_PERIOD_DAYS = 7;
export const GEOFENCE_DEFAULT_RADIUS_METERS = 200;
export const LATE_GRACE_MINUTES = 15;

export const QUOTA_WARNING_THRESHOLD = 0.8;

export const SECTORS = [
  { value: "retail", label: "Commerce / Boutique" },
  { value: "restaurant", label: "Restauration" },
  { value: "beauty", label: "Salon de beauté / Coiffure" },
  { value: "health", label: "Santé / Pharmacie" },
  { value: "education", label: "Éducation / Formation" },
  { value: "construction", label: "Construction / BTP" },
  { value: "logistics", label: "Logistique / Transport" },
  { value: "manufacturing", label: "Industrie / Atelier" },
  { value: "services", label: "Services / Consulting" },
  { value: "technology", label: "Technologie / IT" },
  { value: "agriculture", label: "Agriculture" },
  { value: "other", label: "Autre" },
] as const;

export const COUNTRIES = [
  // --- Afrique de l'Ouest ---
  { code: "CI", name: "🇨🇮 Côte d'Ivoire", timezone: "Africa/Abidjan", currency: "XOF" },
  { code: "SN", name: "🇸🇳 Sénégal", timezone: "Africa/Dakar", currency: "XOF" },
  { code: "ML", name: "🇲🇱 Mali", timezone: "Africa/Bamako", currency: "XOF" },
  { code: "BF", name: "🇧🇫 Burkina Faso", timezone: "Africa/Ouagadougou", currency: "XOF" },
  { code: "BJ", name: "🇧🇯 Bénin", timezone: "Africa/Porto-Novo", currency: "XOF" },
  { code: "TG", name: "🇹🇬 Togo", timezone: "Africa/Lome", currency: "XOF" },
  { code: "NE", name: "🇳🇪 Niger", timezone: "Africa/Niamey", currency: "XOF" },
  { code: "GN", name: "🇬🇳 Guinée", timezone: "Africa/Conakry", currency: "GNF" },
  { code: "GW", name: "🇬🇼 Guinée-Bissau", timezone: "Africa/Bissau", currency: "XOF" },
  { code: "NG", name: "🇳🇬 Nigeria", timezone: "Africa/Lagos", currency: "NGN" },
  { code: "GH", name: "🇬🇭 Ghana", timezone: "Africa/Accra", currency: "GHS" },
  { code: "SL", name: "🇸🇱 Sierra Leone", timezone: "Africa/Freetown", currency: "SLL" },
  { code: "LR", name: "🇱🇷 Liberia", timezone: "Africa/Monrovia", currency: "LRD" },
  { code: "CV", name: "🇨🇻 Cap-Vert", timezone: "Atlantic/Cape_Verde", currency: "CVE" },
  { code: "GM", name: "🇬🇲 Gambie", timezone: "Africa/Banjul", currency: "GMD" },
  { code: "MR", name: "🇲🇷 Mauritanie", timezone: "Africa/Nouakchott", currency: "MRU" },
  // --- Afrique Centrale ---
  { code: "CM", name: "🇨🇲 Cameroun", timezone: "Africa/Douala", currency: "XAF" },
  { code: "GA", name: "🇬🇦 Gabon", timezone: "Africa/Libreville", currency: "XAF" },
  { code: "CG", name: "🇨🇬 Congo-Brazzaville", timezone: "Africa/Brazzaville", currency: "XAF" },
  { code: "CD", name: "🇨🇩 RD Congo", timezone: "Africa/Kinshasa", currency: "CDF" },
  { code: "TD", name: "🇹🇩 Tchad", timezone: "Africa/Ndjamena", currency: "XAF" },
  { code: "CF", name: "🇨🇫 Centrafrique", timezone: "Africa/Bangui", currency: "XAF" },
  { code: "GQ", name: "🇬🇶 Guinée équatoriale", timezone: "Africa/Malabo", currency: "XAF" },
  { code: "ST", name: "🇸🇹 São Tomé-et-Príncipe", timezone: "Africa/Sao_Tome", currency: "STN" },
  // --- Afrique de l'Est ---
  { code: "KE", name: "🇰🇪 Kenya", timezone: "Africa/Nairobi", currency: "KES" },
  { code: "TZ", name: "🇹🇿 Tanzanie", timezone: "Africa/Dar_es_Salaam", currency: "TZS" },
  { code: "UG", name: "🇺🇬 Ouganda", timezone: "Africa/Kampala", currency: "UGX" },
  { code: "RW", name: "🇷🇼 Rwanda", timezone: "Africa/Kigali", currency: "RWF" },
  { code: "BI", name: "🇧🇮 Burundi", timezone: "Africa/Bujumbura", currency: "BIF" },
  { code: "ET", name: "🇪🇹 Éthiopie", timezone: "Africa/Addis_Ababa", currency: "ETB" },
  { code: "DJ", name: "🇩🇯 Djibouti", timezone: "Africa/Djibouti", currency: "DJF" },
  { code: "SO", name: "🇸🇴 Somalie", timezone: "Africa/Mogadishu", currency: "SOS" },
  { code: "ER", name: "🇪🇷 Érythrée", timezone: "Africa/Asmara", currency: "ERN" },
  { code: "SS", name: "🇸🇸 Soudan du Sud", timezone: "Africa/Juba", currency: "SSP" },
  // --- Afrique Australe ---
  { code: "ZA", name: "🇿🇦 Afrique du Sud", timezone: "Africa/Johannesburg", currency: "ZAR" },
  { code: "MZ", name: "🇲🇿 Mozambique", timezone: "Africa/Maputo", currency: "MZN" },
  { code: "ZW", name: "🇿🇼 Zimbabwe", timezone: "Africa/Harare", currency: "ZWL" },
  { code: "ZM", name: "🇿🇲 Zambie", timezone: "Africa/Lusaka", currency: "ZMW" },
  { code: "MW", name: "🇲🇼 Malawi", timezone: "Africa/Lilongwe", currency: "MWK" },
  { code: "BW", name: "🇧🇼 Botswana", timezone: "Africa/Gaborone", currency: "BWP" },
  { code: "NA", name: "🇳🇦 Namibie", timezone: "Africa/Windhoek", currency: "NAD" },
  { code: "AO", name: "🇦🇴 Angola", timezone: "Africa/Luanda", currency: "AOA" },
  { code: "SZ", name: "🇸🇿 Eswatini", timezone: "Africa/Mbabane", currency: "SZL" },
  { code: "LS", name: "🇱🇸 Lesotho", timezone: "Africa/Maseru", currency: "LSL" },
  // --- Afrique du Nord ---
  { code: "MA", name: "🇲🇦 Maroc", timezone: "Africa/Casablanca", currency: "MAD" },
  { code: "TN", name: "🇹🇳 Tunisie", timezone: "Africa/Tunis", currency: "TND" },
  { code: "DZ", name: "🇩🇿 Algérie", timezone: "Africa/Algiers", currency: "DZD" },
  { code: "EG", name: "🇪🇬 Égypte", timezone: "Africa/Cairo", currency: "EGP" },
  { code: "LY", name: "🇱🇾 Libye", timezone: "Africa/Tripoli", currency: "LYD" },
  { code: "SD", name: "🇸🇩 Soudan", timezone: "Africa/Khartoum", currency: "SDG" },
  // --- Îles africaines ---
  { code: "MG", name: "🇲🇬 Madagascar", timezone: "Indian/Antananarivo", currency: "MGA" },
  { code: "MU", name: "🇲🇺 Maurice", timezone: "Indian/Mauritius", currency: "MUR" },
  { code: "SC", name: "🇸🇨 Seychelles", timezone: "Indian/Mahe", currency: "SCR" },
  { code: "KM", name: "🇰🇲 Comores", timezone: "Indian/Comoro", currency: "KMF" },
  { code: "RE", name: "🇷🇪 La Réunion", timezone: "Indian/Reunion", currency: "EUR" },
  { code: "YT", name: "🇾🇹 Mayotte", timezone: "Indian/Mayotte", currency: "EUR" },
  // --- Europe ---
  { code: "FR", name: "🇫🇷 France", timezone: "Europe/Paris", currency: "EUR" },
  { code: "BE", name: "🇧🇪 Belgique", timezone: "Europe/Brussels", currency: "EUR" },
  { code: "CH", name: "🇨🇭 Suisse", timezone: "Europe/Zurich", currency: "CHF" },
  { code: "LU", name: "🇱🇺 Luxembourg", timezone: "Europe/Luxembourg", currency: "EUR" },
  { code: "MC", name: "🇲🇨 Monaco", timezone: "Europe/Monaco", currency: "EUR" },
  { code: "DE", name: "🇩🇪 Allemagne", timezone: "Europe/Berlin", currency: "EUR" },
  { code: "ES", name: "🇪🇸 Espagne", timezone: "Europe/Madrid", currency: "EUR" },
  { code: "PT", name: "🇵🇹 Portugal", timezone: "Europe/Lisbon", currency: "EUR" },
  { code: "IT", name: "🇮🇹 Italie", timezone: "Europe/Rome", currency: "EUR" },
  { code: "NL", name: "🇳🇱 Pays-Bas", timezone: "Europe/Amsterdam", currency: "EUR" },
  { code: "GB", name: "🇬🇧 Royaume-Uni", timezone: "Europe/London", currency: "GBP" },
  { code: "IE", name: "🇮🇪 Irlande", timezone: "Europe/Dublin", currency: "EUR" },
  { code: "AT", name: "🇦🇹 Autriche", timezone: "Europe/Vienna", currency: "EUR" },
  { code: "PL", name: "🇵🇱 Pologne", timezone: "Europe/Warsaw", currency: "PLN" },
  { code: "CZ", name: "🇨🇿 Tchéquie", timezone: "Europe/Prague", currency: "CZK" },
  { code: "SE", name: "🇸🇪 Suède", timezone: "Europe/Stockholm", currency: "SEK" },
  { code: "NO", name: "🇳🇴 Norvège", timezone: "Europe/Oslo", currency: "NOK" },
  { code: "DK", name: "🇩🇰 Danemark", timezone: "Europe/Copenhagen", currency: "DKK" },
  { code: "FI", name: "🇫🇮 Finlande", timezone: "Europe/Helsinki", currency: "EUR" },
  { code: "GR", name: "🇬🇷 Grèce", timezone: "Europe/Athens", currency: "EUR" },
  { code: "RO", name: "🇷🇴 Roumanie", timezone: "Europe/Bucharest", currency: "RON" },
  { code: "BG", name: "🇧🇬 Bulgarie", timezone: "Europe/Sofia", currency: "BGN" },
  { code: "HR", name: "🇭🇷 Croatie", timezone: "Europe/Zagreb", currency: "EUR" },
  { code: "HU", name: "🇭🇺 Hongrie", timezone: "Europe/Budapest", currency: "HUF" },
  { code: "SK", name: "🇸🇰 Slovaquie", timezone: "Europe/Bratislava", currency: "EUR" },
  { code: "SI", name: "🇸🇮 Slovénie", timezone: "Europe/Ljubljana", currency: "EUR" },
  { code: "RS", name: "🇷🇸 Serbie", timezone: "Europe/Belgrade", currency: "RSD" },
  { code: "UA", name: "🇺🇦 Ukraine", timezone: "Europe/Kiev", currency: "UAH" },
  { code: "TR", name: "🇹🇷 Turquie", timezone: "Europe/Istanbul", currency: "TRY" },
  { code: "RU", name: "🇷🇺 Russie", timezone: "Europe/Moscow", currency: "RUB" },
  // --- Amérique du Nord ---
  { code: "US", name: "🇺🇸 États-Unis", timezone: "America/New_York", currency: "USD" },
  { code: "CA", name: "🇨🇦 Canada", timezone: "America/Toronto", currency: "CAD" },
  { code: "MX", name: "🇲🇽 Mexique", timezone: "America/Mexico_City", currency: "MXN" },
  // --- Caraïbes ---
  { code: "HT", name: "🇭🇹 Haïti", timezone: "America/Port-au-Prince", currency: "HTG" },
  { code: "DO", name: "🇩🇴 République dominicaine", timezone: "America/Santo_Domingo", currency: "DOP" },
  { code: "CU", name: "🇨🇺 Cuba", timezone: "America/Havana", currency: "CUP" },
  { code: "JM", name: "🇯🇲 Jamaïque", timezone: "America/Jamaica", currency: "JMD" },
  { code: "TT", name: "🇹🇹 Trinité-et-Tobago", timezone: "America/Port_of_Spain", currency: "TTD" },
  { code: "GP", name: "🇬🇵 Guadeloupe", timezone: "America/Guadeloupe", currency: "EUR" },
  { code: "MQ", name: "🇲🇶 Martinique", timezone: "America/Martinique", currency: "EUR" },
  { code: "GF", name: "🇬🇫 Guyane française", timezone: "America/Cayenne", currency: "EUR" },
  // --- Amérique du Sud ---
  { code: "BR", name: "🇧🇷 Brésil", timezone: "America/Sao_Paulo", currency: "BRL" },
  { code: "AR", name: "🇦🇷 Argentine", timezone: "America/Buenos_Aires", currency: "ARS" },
  { code: "CO", name: "🇨🇴 Colombie", timezone: "America/Bogota", currency: "COP" },
  { code: "CL", name: "🇨🇱 Chili", timezone: "America/Santiago", currency: "CLP" },
  { code: "PE", name: "🇵🇪 Pérou", timezone: "America/Lima", currency: "PEN" },
  { code: "VE", name: "🇻🇪 Venezuela", timezone: "America/Caracas", currency: "VES" },
  { code: "EC", name: "🇪🇨 Équateur", timezone: "America/Guayaquil", currency: "USD" },
  { code: "UY", name: "🇺🇾 Uruguay", timezone: "America/Montevideo", currency: "UYU" },
  { code: "PY", name: "🇵🇾 Paraguay", timezone: "America/Asuncion", currency: "PYG" },
  { code: "BO", name: "🇧🇴 Bolivie", timezone: "America/La_Paz", currency: "BOB" },
  // --- Moyen-Orient ---
  { code: "LB", name: "🇱🇧 Liban", timezone: "Asia/Beirut", currency: "LBP" },
  { code: "AE", name: "🇦🇪 Émirats arabes unis", timezone: "Asia/Dubai", currency: "AED" },
  { code: "SA", name: "🇸🇦 Arabie saoudite", timezone: "Asia/Riyadh", currency: "SAR" },
  { code: "QA", name: "🇶🇦 Qatar", timezone: "Asia/Qatar", currency: "QAR" },
  { code: "KW", name: "🇰🇼 Koweït", timezone: "Asia/Kuwait", currency: "KWD" },
  { code: "BH", name: "🇧🇭 Bahreïn", timezone: "Asia/Bahrain", currency: "BHD" },
  { code: "OM", name: "🇴🇲 Oman", timezone: "Asia/Muscat", currency: "OMR" },
  { code: "JO", name: "🇯🇴 Jordanie", timezone: "Asia/Amman", currency: "JOD" },
  { code: "IQ", name: "🇮🇶 Irak", timezone: "Asia/Baghdad", currency: "IQD" },
  { code: "IL", name: "🇮🇱 Israël", timezone: "Asia/Jerusalem", currency: "ILS" },
  { code: "PS", name: "🇵🇸 Palestine", timezone: "Asia/Gaza", currency: "ILS" },
  { code: "YE", name: "🇾🇪 Yémen", timezone: "Asia/Aden", currency: "YER" },
  { code: "SY", name: "🇸🇾 Syrie", timezone: "Asia/Damascus", currency: "SYP" },
  { code: "IR", name: "🇮🇷 Iran", timezone: "Asia/Tehran", currency: "IRR" },
  // --- Asie ---
  { code: "IN", name: "🇮🇳 Inde", timezone: "Asia/Kolkata", currency: "INR" },
  { code: "CN", name: "🇨🇳 Chine", timezone: "Asia/Shanghai", currency: "CNY" },
  { code: "JP", name: "🇯🇵 Japon", timezone: "Asia/Tokyo", currency: "JPY" },
  { code: "KR", name: "🇰🇷 Corée du Sud", timezone: "Asia/Seoul", currency: "KRW" },
  { code: "ID", name: "🇮🇩 Indonésie", timezone: "Asia/Jakarta", currency: "IDR" },
  { code: "TH", name: "🇹🇭 Thaïlande", timezone: "Asia/Bangkok", currency: "THB" },
  { code: "VN", name: "🇻🇳 Vietnam", timezone: "Asia/Ho_Chi_Minh", currency: "VND" },
  { code: "PH", name: "🇵🇭 Philippines", timezone: "Asia/Manila", currency: "PHP" },
  { code: "MY", name: "🇲🇾 Malaisie", timezone: "Asia/Kuala_Lumpur", currency: "MYR" },
  { code: "SG", name: "🇸🇬 Singapour", timezone: "Asia/Singapore", currency: "SGD" },
  { code: "PK", name: "🇵🇰 Pakistan", timezone: "Asia/Karachi", currency: "PKR" },
  { code: "BD", name: "🇧🇩 Bangladesh", timezone: "Asia/Dhaka", currency: "BDT" },
  { code: "LK", name: "🇱🇰 Sri Lanka", timezone: "Asia/Colombo", currency: "LKR" },
  { code: "NP", name: "🇳🇵 Népal", timezone: "Asia/Kathmandu", currency: "NPR" },
  { code: "MM", name: "🇲🇲 Myanmar", timezone: "Asia/Yangon", currency: "MMK" },
  { code: "KH", name: "🇰🇭 Cambodge", timezone: "Asia/Phnom_Penh", currency: "KHR" },
  { code: "LA", name: "🇱🇦 Laos", timezone: "Asia/Vientiane", currency: "LAK" },
  { code: "AF", name: "🇦🇫 Afghanistan", timezone: "Asia/Kabul", currency: "AFN" },
  { code: "UZ", name: "🇺🇿 Ouzbékistan", timezone: "Asia/Tashkent", currency: "UZS" },
  { code: "KZ", name: "🇰🇿 Kazakhstan", timezone: "Asia/Almaty", currency: "KZT" },
  { code: "GE", name: "🇬🇪 Géorgie", timezone: "Asia/Tbilisi", currency: "GEL" },
  { code: "AZ", name: "🇦🇿 Azerbaïdjan", timezone: "Asia/Baku", currency: "AZN" },
  { code: "AM", name: "🇦🇲 Arménie", timezone: "Asia/Yerevan", currency: "AMD" },
  // --- Océanie ---
  { code: "AU", name: "🇦🇺 Australie", timezone: "Australia/Sydney", currency: "AUD" },
  { code: "NZ", name: "🇳🇿 Nouvelle-Zélande", timezone: "Pacific/Auckland", currency: "NZD" },
  { code: "FJ", name: "🇫🇯 Fidji", timezone: "Pacific/Fiji", currency: "FJD" },
  { code: "PF", name: "🇵🇫 Polynésie française", timezone: "Pacific/Tahiti", currency: "XPF" },
  { code: "NC", name: "🇳🇨 Nouvelle-Calédonie", timezone: "Pacific/Noumea", currency: "XPF" },
] as const;
